language: node_js
node_js:
  - 0.8
before_script:
  - npm install -g grunt-cli
  - sudo apt-get install -qq strace
  - sudo apt-get install tofrodos
  - find lib/flex_sdk/ -type f -exec dos2unix {} \;
